language: java
jdk:
  - oraclejdk8
dist: trusty
install:
  - export HUGO_VERSION=0.48
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb"
  - sudo dpkg -i "hugo_${HUGO_VERSION}_Linux-64bit.deb"
  - nvm install 8
script:
  - cd ./app && yarn run build
  - cd ../ && ./docs.sh
  - hugo
branches:
  only:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
cache:
  - yarn
